name = "redir"
main = "./src/index.js"
# dist if using webpack
# main = "dist/worker.js"
# 2024-09-23 is min for nodejs_compat_v2 which supports AsyncLocalStorage
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true
send_metrics = false
upload_source_maps = true

# update vars in d.js for snippets compat
[vars]
REDIR_CATCHALL = "https://rethinkdns.com/404#r"
WENV = "dev"
MIN_VCODE = "30"
MIN_VCODE_PAID_FEATURES = "46"
WS_URL_TEST = "https://api-staging.windscribe.com/"
WS_URL = "https://api.windscribe.com/"
STATUS = "ok"

# [build]
# command = "npx webpack"
# cwd = "."

# developers.cloudflare.com/d1/configuration/environments
[[d1_databases]]
binding = "REDIRDBTEST"
database_name = "rpntest"
database_id = "e6db9d1f-cf58-427e-aa15-bd3fbf54d69e"

[[d1_databases]]
binding = "REDIRDB"
database_name = "rpn"
database_id = "fa48c37b-1a08-43c6-8644-536d21b5513d"


##################
#------PROD------#
##################
[env.prod]
name = "svc"
minify = true
main = "./dist/worker.js"
routes = [
  # redirects
  "svc.rethinkdns.com/r/*",
  "svc.bravedns.com/r/*",
  # stripe webhooks
  "svc.rethinkdns.com/s/*",
  "svc.bravedns.com/s/*",
  # order
  "svc.rethinkdns.com/mb/*",
  "svc.bravedns.com/mt/*",
  # proxy
  "svc.rethinkdns.com/p/*",
  "svc.bravedns.com/p/*",
  # google rtdn webhook
  "svc.rethinkdns.com/g/*",
  "svc.bravedns.com/g/*",
]

# update vars in d.js for snippets compat
# vars are not inherited
# workers/platform/environment-variables#environment-variables-via-wrangler
[env.prod.vars]
REDIR_CATCHALL = "https://rethinkdns.com/404#r"
WENV = "prod"
MIN_VCODE = "30"
MIN_VCODE_PAID_FEATURES = "46"
WS_URL_TEST = "https://api-staging.windscribe.com/"
WS_URL = "https://api.windscribe.com/"
STATUS = "ok"

[[d1_databases]]
binding = "SVCDBTEST"
database_name = "rpntest"
database_id = "e6db9d1f-cf58-427e-aa15-bd3fbf54d69e"

[[d1_databases]]
binding = "SVCDB"
database_name = "rpn"
database_id = "fa48c37b-1a08-43c6-8644-536d21b5513d"

##################
#-----SECRETS----#
##################
# only for documentation purposes
# developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler
# [secrets]
# STRIPE_API_KEY = "sk_live_..."
# STRIPE_WEBHOOK_SECRET = "whsec_..."
# PRE_SHARED_KEY_SVC = "128-chars-hex"
# PUBLIC_KEY_BLINDRSA_(timestamp) = "pub-rsa-pss-hex"
# developers.google.com/maps/documentation/geocoding/get-api-key#restrict_key
# GMAPS_API_KEY = "base64..."
# console.cloud.google.com/iam-admin/serviceaccounts/details
# key id: f0123c59fbad
# GCP_REDIR_SVC_CREDS = "json with private key"
# KDF key for D1 enc-at-rest; same ID must have same secret
# for both prod and test (see: DB/DBTEST bindings)
# KDF_SECRET_D1 = "64-chars-hex..."
# KDF_SECRET_D1_TEST = "64-chars-hex..."
# KDF key for encrypted payloads sent publicly
# KDF_SECRET_CLIENT = "64-chars-hex..."
# KDF_SECRET_CLIENT_TEST = "64-chars-hex..."
# KDF key for cross-service calls (from max, for example)
# KDF_XSVC = "64-chars-hex..."
# Emergency alternative TLS cert
# FLY_TLS_CERTKEY = file(KEY=$B64NOWRAP_KEY\nCRT=$B64NOWRAP_CERT\n)
# WS api keys
# WS_WL_ID = "string"
# WS_WL_TOKEN = "string"
# WS_WL_ID_TEST = "string"
# WS_WL_TOKEN_TEST = "string"


# update secrets in d.js for snippets compat
