CREATE TABLE IF NOT EXISTS clients (
    cid TEXT PRIMARY KEY,
    -- json blob representing this client
    meta TEXT,
    -- 0 for playclient, 1 playserver, 2 for stripe
    kind INTEGER,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- last updated at timestamp
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE IF NOT EXISTS playorders (
    purchasetoken TEXT PRIMARY KEY,
    -- json blob representing this order
    -- todo: use generated cols? developers.cloudflare.com/d1/reference/generated-columns/
    meta TEXT,
    -- client id, may be generated by the client or server
    cid TEXT NOT NULL,
    -- linked purchase token, if any
    linkedtoken TEXT,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS stripeorders (
    sid TEXT PRIMARY KEY,
    -- product identifier
    prod TEXT,
    -- json blob representing this order
    meta TEXT,
    -- client id, never null
    cid TEXT NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS ws (
    -- client identifier
    cid TEXT PRIMARY KEY,
    -- ws session token (encrypted)
    sessiontoken TEXT NOT NULL ,
    -- user identifier
    userid TEXT NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    -- restrict deletion unless ws has been notified and sessiontoken is invalidated
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE RESTRICT,
)
