CREATE TABLE IF NOT EXISTS clients (
    cid TEXT PRIMARY KEY,
    -- json blob representing this client
    meta TEXT,
    -- 0 for playclient, 1 playserver, 2 for stripe; -1 for banned, -2 for removed
    kind INTEGER,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- last updated at timestamp
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS devices (
    did TEXT PRIMARY KEY,
    -- json blob representing this device
    cid TEXT NOT NULL,
    -- meta blob, sent by the client
    meta TEXT,
    -- 0 for phone, 1 for tv; -1 for banned, -2 for removed
    kind INTEGER,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- last updated at timestamp
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS playorders (
    purchasetoken TEXT PRIMARY KEY,
    -- json blob representing this order
    -- todo: use generated cols? developers.cloudflare.com/d1/reference/generated-columns/
    meta TEXT,
    -- client id, may be generated by the client or server
    cid TEXT NOT NULL,
    -- linked purchase token, if any
    linkedtoken TEXT,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stripeorders (
    sid TEXT PRIMARY KEY,
    -- product identifier
    prod TEXT,
    -- json blob representing this order
    meta TEXT,
    -- client id, never null
    cid TEXT NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ws (
    -- client identifier
    cid TEXT PRIMARY KEY,
    -- ws session token (encrypted)
    sessiontoken TEXT NOT NULL,
    -- user identifier (todo: unique)
    userid TEXT NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- restrict deletion unless ws has been notified and sessiontoken is invalidated
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS wslease (
    -- user identifier
    userid TEXT PRIMARY KEY,
    -- ws session token (encrypted)
    sessiontoken TEXT NOT NULL,
    -- session information json
    meta TEXT NOT NULL,
    -- client identifier
    cid TEXT UNIQUE,
    -- expiry
    until TIMESTAMP NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- restrict deletion unless ws has been notified and sessiontoken is invalidated
    FOREIGN KEY (cid) REFERENCES clients(cid) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS wsperma (
    -- managed wg public key (std base64; 44 chars)
    pubkey TEXT PRIMARY KEY,
    -- device identifier; nullable: set to NULL by FK ON DELETE SET NULL when device is removed
    did TEXT UNIQUE,
    -- client identifier
    cid TEXT NOT NULL,
    -- credential as json (encrypted)
    meta TEXT NOT NULL,
    -- created at timestamp
    ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (did) REFERENCES devices(did) ON DELETE SET NULL,
    FOREIGN KEY (cid) REFERENCES ws(cid) ON DELETE CASCADE
);

-- developers.cloudflare.com/d1/best-practices/use-indexes
CREATE INDEX IF NOT EXISTS idx_playorders_linkedtoken
ON playorders(linkedtoken);

CREATE INDEX IF NOT EXISTS idx_playorders_cid
ON playorders(cid);

CREATE INDEX IF NOT EXISTS idx_devices_cid
ON devices(cid);

CREATE INDEX IF NOT EXISTS idx_wslease_cid
ON wslease(cid);

CREATE INDEX IF NOT EXISTS idx_wsperma_cid
ON wsperma(cid);

-- sqlite.org/foreignkeys.html
-- TODO: migrate tables with unique constraints on columns that
-- TODO: require it for it to be a valid foreign key