/*
 * Copyright (c) 2026 RethinkDNS and its authors.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import { LfuCache } from "@serverless-dns/lfu-cache";
import {
  buf2hex,
  cat,
  emptyString,
  hex2buf,
  lcat,
  safeEq,
  str2byte,
} from "./buf.js";
import { ResClientReg, ResDevice, ResDeviceList } from "./d.js";
import { hmacclientkey } from "./enc.js";
import { hmacsign } from "./hmac.js";
import * as glog from "./log.js";
import {
  consumejson,
  didTokenHeader,
  r200j,
  r204,
  r204token,
  r400err as r400,
  r401err as r401,
  r404err as r404,
  r405err as r405,
  r500err as r500,
} from "./req.js";
import * as dbx from "./sql/dbx.js";
import { crand, obfuscateHex } from "./webcrypto.js";

// TODO: set it to false once all test clients have migrated to the new registration flow
const allowAuthorizationBypassForTest = false;

export const mincidlength = 32; // ideally 64 hex chars
export const mindidlength = 16; // ideally 32 hex chars

const kindplaystoreclient = 0;

const kindphone = 0;
// const kindbanned = -1;
const kindremoved = -2;
const log = new glog.Log("reg");

const clientmsg = str2byte("rethinkappclient");
const devicemsg = str2byte("rethinkappdevice");

// Sig cache: key = hex(rand16)[+hex(rand8)]+":t"/":p", value = "valid"|"invalid"
// Caches whether a given cid (rand16) or did (rand16+rand8) HMAC signature passed.
// get() returns false (boolean) on cache miss, so "valid"/"invalid" strings are
// used to distinguish a cached result from a miss.
const sigcache = new LfuCache("regsig", 6_000);

// Token cache: key = cid+":"+did+":"+expiryEpoch, value = expected-sig-hex
// Caches the HMAC sig computed for a did token so re-verification skips hmacsign.
const didtokencache = new LfuCache("regtok", 3_000);

const sigok = "valid";
const signotok = "invalid";

/**
 * Cache key for the cid HMAC sig (covers rand16 component of a cid).
 * @param {Uint8Array} rand16
 * @param {boolean} test
 * @returns {string}
 */
function sigkey1(rand16, test) {
  return buf2hex(rand16) + (test ? ":t" : ":p");
}

/**
 * Cache key for the did HMAC sig (covers rand16 from cid + rand8 from did).
 * @param {Uint8Array} rand16
 * @param {Uint8Array} rand8
 * @param {boolean} test
 * @returns {string}
 */
function sigkey2(rand16, rand8, test) {
  return buf2hex(rand16) + buf2hex(rand8) + (test ? ":t" : ":p");
}

/**
 * Cache key for a did token.
 * @param {string} cid
 * @param {string} did
 * @param {number} expiry - epoch seconds
 * @returns {string}
 */
function didtokkey(cid, did, expiry) {
  return `${cid}:${did}:${expiry}`;
}

// Adjustable validity period for the did token; default 3 days
const didTokenValiditySecs = 3 * 24 * 60 * 60;
const didTokenCtx = str2byte("rethinkappdidtoken");

/**
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request
 */
export async function registerClient(env, req) {
  if (req.method !== "POST") {
    return r405("method not allowed");
  }
  const url = new URL(req.url);
  const test = url.searchParams.has("test");
  const clientkind = url.searchParams.get("clientkind") || "0";
  const devicekind = url.searchParams.get("devicekind") || "0";
  const existingCid = url.searchParams.get("cid");
  const meta = await consumejson(req);

  const parsedck = parseInt(clientkind, 10);
  const parseddk = parseInt(devicekind, 10);
  const clientkindint = !isNaN(parsedck) ? parsedck : kindplaystoreclient;
  const devicekindint = !isNaN(parseddk) ? parseddk : kindphone;

  // if a cid is provided, verify it was generated by us, then upsert client metadata only
  if (!emptyString(existingCid)) {
    if (
      existingCid.length < mincidlength ||
      !/^[a-fA-F0-9]+$/.test(existingCid)
    ) {
      return r400("invalid cid");
    }

    // re-derive the hmac key from the prefix half of the cid and verify the suffix
    const cidBytes = hex2buf(existingCid);
    const rand16 = cidBytes.slice(0, 16);
    const cidsig16claimed = cidBytes.slice(16, 32);

    // check sig cache before performing hmac
    const cidkey = sigkey1(rand16, test);
    const cachedCidSig = sigcache.get(cidkey);
    if (cachedCidSig === signotok) {
      log.w("registerClient: cid sig cached invalid", existingCid);
      return r401("cid verification failed");
    }
    if (cachedCidSig === false) {
      // cache miss: run hmac and store result
      try {
        const k = await hmacclientkey(env, rand16, test);
        if (!k) {
          return r500("k unavailable");
        }
        const cidmsg = cat(rand16, clientmsg);
        const cidsigbuf = await hmacsign(k, cidmsg);
        const cidsig16expected = new Uint8Array(cidsigbuf).slice(0, 16);
        const valid = safeEq(cidsig16claimed, cidsig16expected);
        sigcache.put(cidkey, valid ? sigok : signotok);
        if (!valid) {
          log.w("registerClient: cid invalid", existingCid);
          return r401("cid verification failed");
        }
      } catch (e) {
        log.e("registerClient: cid verify error:", e);
        return r500(`cid verify error: ${e.message}`);
      }
    }

    const clientmeta = meta?.client ?? null;
    try {
      const db = dbx.db(env);
      const cout = await dbx.upsertClient(
        db,
        existingCid,
        clientmeta,
        clientkindint,
      );
      if (cout == null || !cout.success) {
        log.w(`registerClient upsert failed for ${existingCid}, test? ${test}`);
        return r500("could not re-register");
      }
    } catch (e) {
      log.e("registerClient upsert error:", e);
      return r500(`db err: ${e.message}`);
    }

    log.d("registerClient updated cid:", existingCid, "test?", test);
    return r200j(new ResClientReg({ cid: existingCid }).json);
  }

  try {
    const rand = crand(24);
    const rand16 = rand.slice(0, 16);
    const rand8 = rand.slice(16, 24);

    const k = await hmacclientkey(env, rand16, test);
    if (!k) {
      return r500("k unavailable");
    }

    const cidmsg = cat(rand16, clientmsg);
    const didmsg = cat(rand8, devicemsg);

    const allsigs = await Promise.all([
      hmacsign(k, cidmsg),
      hmacsign(k, didmsg),
    ]);

    const cidsig16 = new Uint8Array(allsigs[0]).slice(0, 16);
    const didsig8 = new Uint8Array(allsigs[1]).slice(0, 8);

    const cid = buf2hex(cat(rand16, cidsig16));
    const did = buf2hex(cat(rand8, didsig8));

    const clientmeta = meta?.client ?? null;
    const devicemeta = meta?.device ?? null;

    const db = dbx.db(env);
    const cout = await dbx.insertClient(db, cid, clientmeta, clientkindint);
    if (cout == null || !cout.success) {
      return r500("client insert failed");
    }
    const dout = await dbx.upsertDevice(
      db,
      did,
      cid,
      devicemeta,
      devicekindint,
    );
    if (dout == null || !dout.success) {
      // TODO: delete cid from clients table since device insert failed,
      // to avoid orphaned client record
      return r500("device insert failed");
    }
    log.d("registerClient cid:", cid, "did:", did, "test?", test);
    return r200j(new ResClientReg({ cid, did }).json);
  } catch (e) {
    log.e("registerClient error:", e);
    return r500(`db error: ${e.message}`);
  }
}

/**
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request
 */
export async function registerDevice(env, req) {
  if (req.method !== "POST") {
    return r405("method not allowed");
  }
  if (!req.headers.get("Content-Type")?.includes("application/json")) {
    return r400("unsupported content type");
  }

  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400("missing/invalid cid");
  }

  // verify cid was generated by us
  const cidBytes = hex2buf(cid);
  const rand16 = cidBytes.slice(0, 16);
  const cidsig16claimed = cidBytes.slice(16, 32);

  // pre-parse did bytes (when provided) so cid+did sigs can run in parallel
  let rand8 = null;
  let didsig8claimed = null;
  if (!emptyString(did)) {
    if (did.length < mindidlength || !/^[a-fA-F0-9]+$/.test(did)) {
      return r400("invalid did");
    }
    const didBytes = hex2buf(did);
    rand8 = didBytes.slice(0, 8);
    didsig8claimed = didBytes.slice(8, 16);
  }

  // check sig caches before hmac computation
  const cidkey = sigkey1(rand16, test);
  const didkey = rand8 != null ? sigkey2(rand16, rand8, test) : null;
  const cachedCidSig = sigcache.get(cidkey);
  const cachedDidSig = didkey != null ? sigcache.get(didkey) : null;

  if (cachedCidSig === signotok) {
    return r401("cid verification failed");
  }
  if (cachedDidSig === signotok) {
    return r401("did verification failed");
  }

  // derive key (always needed: uncached sig verification and/or new did generation)
  let k;
  try {
    k = await hmacclientkey(env, rand16, test);
    if (!k) return r500("k unavailable");
  } catch (e) {
    log.e("registerDevice: key error:", e);
    return r500(`key error: ${e.message}`);
  }

  // verify only the sigs not already cached
  const needCidVerify = cachedCidSig !== sigok;
  const needDidVerify = cachedDidSig !== sigok && rand8 != null;

  if (needCidVerify || needDidVerify) {
    try {
      const tasks = [];
      if (needCidVerify) tasks.push(hmacsign(k, cat(rand16, clientmsg)));
      if (needDidVerify) tasks.push(hmacsign(k, cat(rand8, devicemsg)));
      const results = await Promise.all(tasks);

      let idx = 0;
      if (needCidVerify) {
        const cidsig16expected = new Uint8Array(results[idx++]).slice(0, 16);
        const valid = safeEq(cidsig16claimed, cidsig16expected);
        sigcache.put(cidkey, valid ? sigok : signotok);
        if (!valid) {
          log.w("registerDevice: cid invalid", cid);
          return r401("cid verification failed");
        }
      }
      if (needDidVerify) {
        const didsig8expected = new Uint8Array(results[idx]).slice(0, 8);
        const valid = safeEq(didsig8claimed, didsig8expected);
        sigcache.put(didkey, valid ? sigok : signotok);
        if (!valid) {
          log.w("registerDevice: did invalid", did);
          return r401("did verification failed");
        }
      }
    } catch (e) {
      log.e("registerDevice: sig verify error:", e);
      return r500(`sig verify error: ${e.message}`);
    }
  }

  const meta = await consumejson(req);
  const clientmeta = meta?.client ?? null;
  const devicemeta = meta?.device ?? null;

  if (!emptyString(did)) {
    // both cid and did provided: upsert both tables (sigs already verified above)
    try {
      const db = dbx.db(env);
      const cout = await dbx.upsertClient(
        db,
        cid,
        clientmeta,
        kindplaystoreclient,
      );
      if (cout == null || !cout.success) {
        return r500("client upsert failed");
      }
      const dout = await dbx.upsertDevice(db, did, cid, devicemeta, kindphone);
      if (dout == null || !dout.success) {
        return r500("device upsert failed");
      }
    } catch (e) {
      log.e("registerDevice upsert error:", e);
      return r500(`db error: ${e.message}`);
    }

    log.d("registerDevice updated cid:", cid, "did:", did, "test?", test);
    return retrieveDevices(env, cid, test);
  }

  // only cid provided: generate a new did
  try {
    const rand8 = crand(8);
    const didmsg = cat(rand8, devicemsg);
    const didsigbuf = await hmacsign(k, didmsg);
    const didsig8 = new Uint8Array(didsigbuf).slice(0, 8);
    const newdid = buf2hex(cat(rand8, didsig8));

    const db = dbx.db(env);
    const cout = await dbx.upsertClient(
      db,
      cid,
      clientmeta,
      kindplaystoreclient,
    );
    if (cout == null || !cout.success) {
      return r500("client upsert failed");
    }
    const dout = await dbx.upsertDevice(db, newdid, cid, devicemeta, kindphone);
    if (dout == null || !dout.success) {
      return r500("device insert failed");
    }

    log.d("registerDevice new did:", newdid, "for c:", cid, "test?", test);
    return r200j(new ResClientReg({ cid, did: newdid }).json);
  } catch (e) {
    // ex: Error: D1_ERROR: FOREIGN KEY constraint failed: SQLITE_CONSTRAINT
    log.e("registerDevice error:", e);
    return r500(`db error: ${e.message}`);
  }
}

/**
 * @param {any} env - Workers environment
 * @param {string} cid - Client identifier
 * @param {boolean} test - Test domain?
 */
export async function retrieveDevices(env, cid, test) {
  if (
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400("invalid cid");
  }

  const db = dbx.db(env);
  const out = await dbx.getDevices(db, cid);

  log.d("get dev for c:", cid, "test?", test, "found", out.success);

  if (out == null || !out.success) {
    return r500("database error");
  }
  if (out.results == null || out.results.length <= 0) {
    return r404("no devices found");
  }

  const devices = [];
  for (const entry of out.results) {
    const did = entry.did || "";
    const obs = !emptyString(did) ? await obfuscateHex(did) : "";
    const meta = entry.meta != null ? JSON.parse(entry.meta) : null;
    const ctime =
      entry.ctime != null ? new Date(entry.ctime).toISOString() : null;
    const mtime =
      entry.mtime != null ? new Date(entry.mtime).toISOString() : null;
    devices.push(
      new ResDevice({ did: obs, meta, created: ctime, updated: mtime }),
    );
  }
  return r200j(new ResDeviceList({ devices, test }).json);
}

/**
 * Removes (soft-deletes) a device for the given client.
 * Sets kind = -2 on the device row so it is no longer active or enumerable.
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request with cid and did as query params
 * @returns {Promise<Response>}
 */
export async function removeDevice(env, req) {
  if (req.method !== "DELETE" && req.method !== "POST") {
    return r405("method not allowed");
  }

  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (
    emptyString(did) ||
    did.length < mindidlength ||
    !/^[a-fA-F0-9]+$/.test(did) ||
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400("invalid identifiers");
  }

  try {
    const db = dbx.db(env);
    // kind = -2 marks device as removed (soft-delete)
    const out = await dbx.modifyDeviceKind(db, cid, did, kindremoved);
    if (out == null || !out.success || out.meta?.rowswritten === 0) {
      log.w(
        `removeDevice: no device found for c:${cid} d:${did} test?${test}; out: ${JSON.stringify(out)}`,
      );
      return r404("device not found");
    }
  } catch (e) {
    log.e("removeDevice error:", e);
    return r500(`db error: ${e.message}`);
  }

  log.d("remove", did, "for c:", cid, "test?", test);
  return r204(); // no content
}

/**
 * Returns the current time as a positive integer (Unix epoch seconds).
 * @returns {number}
 */
function unixsec() {
  return (Date.now() / 1000) >>> 0;
}

/**
 * Encodes an epoch (seconds) as a 4-byte big-endian Uint8Array.
 * @param {number} epochSecs
 * @returns {Uint8Array}
 */
function epoch2buf(epochSecs) {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, epochSecs >>> 0, false);
  return b;
}

/**
 * Generates a HMAC token binding cid and did with an expiry timestamp.
 * Token format: "<hmac_hex>:<expiry_epoch_secs>"
 * @param {CryptoKey} k - HMAC key (derived from cid's rand16 via hmacclientkey)
 * @param {string} cid - client id (hex)
 * @param {string} did - device id (hex)
 * @param {number} [validitySecs] - validity in seconds (default: didTokenValiditySecs)
 * @returns {Promise<string|null>} - token string or null on error
 */
async function generateDidToken(
  k,
  cid,
  did,
  validitySecs = didTokenValiditySecs,
) {
  try {
    const expiry = unixsec() + validitySecs;
    const msg = lcat(
      didTokenCtx,
      hex2buf(cid),
      hex2buf(did),
      epoch2buf(expiry),
    );
    const sigbuf = await hmacsign(k, msg);
    const sig = buf2hex(new Uint8Array(sigbuf));
    // populate token cache so subsequent verifications skip hmacsign
    didtokencache.put(didtokkey(cid, did, expiry), sig);
    return `${sig}:${expiry}`;
  } catch (e) {
    log.e("generateDidToken err:", e);
    return null;
  }
}

/**
 * Verifies a did token. Returns true only if the HMAC is valid and the token hasn't expired.
 * @param {CryptoKey} k - HMAC key (derived from cid's rand16 via hmacclientkey)
 * @param {string} cid - client id (hex)
 * @param {string} did - device id (hex)
 * @param {string} token - token string "<hmac_hex>:<expiry_epoch_secs>"
 * @returns {Promise<boolean>}
 */
async function verifyDidToken(k, cid, did, token) {
  try {
    const sep = token.lastIndexOf(":");
    if (sep < 0) return false;
    const claimedSigHex = token.slice(0, sep);
    const claimedExpiry = parseInt(token.slice(sep + 1), 10);
    if (isNaN(claimedExpiry) || claimedExpiry <= unixsec()) {
      return false; // expired or unparseable
    }
    // token cache fast path: if we've already computed the expected sig for
    // this (cid, did, expiry), compare directly without another hmacsign
    const tkey = didtokkey(cid, did, claimedExpiry);
    const cachedSig = didtokencache.get(tkey);
    if (cachedSig !== false) {
      return cachedSig === claimedSigHex;
    }
    // cache miss: compute expected sig, store it, then compare
    const msg = lcat(
      didTokenCtx,
      hex2buf(cid),
      hex2buf(did),
      epoch2buf(claimedExpiry),
    );
    const expectedSigBuf = await hmacsign(k, msg);
    const expectedSig = new Uint8Array(expectedSigBuf);
    const expectedSigHex = buf2hex(expectedSig);
    didtokencache.put(tkey, expectedSigHex);
    const claimedSig = hex2buf(claimedSigHex);
    return safeEq(claimedSig, expectedSig);
  } catch (e) {
    log.e("verifyDidToken err:", e);
    return false;
  }
}

/**
 * Verifies that the device (did) is registered for the client (cid) and isn't banned.
 * First verifies cid and did were generated by us (via the HMAC flow) before touching the DB.
 * If the request carries a valid "x-rethink-app-did-token" header the database check is
 * skipped entirely. On a successful database check a fresh token is minted and returned in
 * the "x-rethink-app-did-token" response header.
 * Callers should check resp.ok: false means the request is denied.
 * @param {any} env - Worker environment
 * @param {Request} req - The incoming request containing cid and did query parameters
 * @returns {Promise<Response>} 204 if authorized (token in header on new issue), error Response otherwise.
 */
export async function authorizeDevice(env, req) {
  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (!cid || cid.length < mincidlength || !/^[a-fA-F0-9]+$/.test(cid)) {
    return r400("missing/invalid client id");
  }
  if (!did || did.length < mindidlength || !/^[a-fA-F0-9]+$/.test(did)) {
    return r400("missing/invalid device id");
  }

  // parse id bytes upfront so cache keys and sigs can be computed
  const cidBytes = hex2buf(cid);
  const rand16 = cidBytes.slice(0, 16);
  const cidsig16claimed = cidBytes.slice(16, 32);

  const didBytes = hex2buf(did);
  const rand8 = didBytes.slice(0, 8);
  const didsig8claimed = didBytes.slice(8, 16);

  // check sig caches before any crypto
  const cidkey = sigkey1(rand16, test);
  const didkey = sigkey2(rand16, rand8, test);
  const cachedCidSig = sigcache.get(cidkey);
  const cachedDidSig = sigcache.get(didkey);

  if (cachedCidSig === signotok) {
    log.w("authorizeDevice: cid sig cached invalid", cid);
    if (allowAuthorizationBypassForTest && test) {
      log.w("authorizeDevice: TEST bypass cid sig invalid");
      return r204();
    }
    return r401("missing/invalid client id");
  }
  if (cachedDidSig === signotok) {
    log.w("authorizeDevice: did sig cached invalid", did);
    if (allowAuthorizationBypassForTest && test) {
      log.w("authorizeDevice: TEST bypass did sig invalid");
      return r204();
    }
    return r401("missing/invalid device id");
  }

  const incomingToken = req.headers.get(didTokenHeader);

  // ultra-fast path: both sigs cached valid + matching token in tokenCache →
  // authorized with no key derivation or hmacsign at all
  if (
    !emptyString(incomingToken) &&
    cachedCidSig === sigok &&
    cachedDidSig === sigok
  ) {
    const sep = incomingToken.lastIndexOf(":");
    if (sep >= 0) {
      const claimedSigHex = incomingToken.slice(0, sep);
      const claimedExpiry = parseInt(incomingToken.slice(sep + 1), 10);
      if (!isNaN(claimedExpiry) && claimedExpiry > unixsec()) {
        const cachedTokSig = didtokencache.get(
          didtokkey(cid, did, claimedExpiry),
        );
        if (cachedTokSig === claimedSigHex) {
          log.d("authorizeDevice: sig+token cached ok", cid, ":", did);
          return r204();
        }
      }
    }
  }

  // derive key (needed for: uncached sig verification, verifyDidToken, generateDidToken)
  let k;
  try {
    k = await hmacclientkey(env, rand16, test);
    if (!k) return r500("k unavailable");
  } catch (e) {
    log.e("authorizeDevice: key error:", e);
    return r500(`key error: ${e.message}`);
  }

  // verify only the sigs not already cached
  const needCidVerify = cachedCidSig !== sigok;
  const needDidVerify = cachedDidSig !== sigok;

  if (needCidVerify || needDidVerify) {
    try {
      const tasks = [];
      if (needCidVerify) tasks.push(hmacsign(k, cat(rand16, clientmsg)));
      if (needDidVerify) tasks.push(hmacsign(k, cat(rand8, devicemsg)));
      const results = await Promise.all(tasks);

      let idx = 0;
      if (needCidVerify) {
        const cidsig16expected = new Uint8Array(results[idx++]).slice(0, 16);
        const valid = safeEq(cidsig16claimed, cidsig16expected);
        sigcache.put(cidkey, valid ? sigok : signotok);
        if (!valid) {
          log.w("authorizeDevice: cid invalid", cid);
          if (allowAuthorizationBypassForTest && test) {
            log.w("authorizeDevice: TEST bypass cid invalid");
            return r204();
          }
          return r401("missing/invalid client id");
        }
      }
      if (needDidVerify) {
        const didsig8expected = new Uint8Array(results[idx]).slice(0, 8);
        const valid = safeEq(didsig8claimed, didsig8expected);
        sigcache.put(didkey, valid ? sigok : signotok);
        if (!valid) {
          log.w("authorizeDevice: did invalid", did);
          if (allowAuthorizationBypassForTest && test) {
            log.w("authorizeDevice: TEST bypass did invalid");
            return r204();
          }
          return r401(`missing/invalid device id`);
        }
      }
    } catch (e) {
      log.e("authorizeDevice: sig error:", e);
      return r500(`${e.message}`);
    }
  }

  // token fast path: skip the database if the client presents a valid did token
  if (!emptyString(incomingToken)) {
    const valid = await verifyDidToken(k, cid, did, incomingToken);
    if (valid) {
      log.d("authorizeDevice: token ok for", cid, ":", did);
      return r204(); // authorized; existing token still valid, no re-issue needed
    }
    log.d("authorizeDevice: token invalid/expired", cid, ":", did);
  }

  // fallback: verify via database
  let devres;
  try {
    devres = await dbx.getDevice(dbx.db(env), cid, did);
  } catch (ex) {
    return r500(`db err: ${ex.message}`);
  }

  log.d("authorize:", cid, ":", did, "t?", test, "ok?", devres?.success);

  // getDevice excludes banned devices (kind != -1) and matches both cid+did;
  // no result means the device is unregistered or banned.
  if (
    devres == null ||
    !devres.success ||
    devres.results == null ||
    devres.results.length <= 0
  ) {
    if (allowAuthorizationBypassForTest && test) {
      log.w(`authorizeDevice: TEST bypass device not found ${cid}: ${did}`);
      return r204();
    }
    return r401("device not found");
  }

  // device authorized via db: mint and return a fresh token
  const token = await generateDidToken(k, cid, did);
  if (emptyString(token)) {
    log.w("authorizeDevice: token gen err for", cid, ":", did);
    return r204(); // authorized but token issuance failed; proceed without it
  }
  return r204token(token);
}
