/*
 * Copyright (c) 2026 RethinkDNS and its authors.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import {
  buf2hex,
  cat,
  emptyString,
  hex2buf,
  lcat,
  safeEq,
  str2byte,
} from "./buf.js";
import { hmacclientkey } from "./enc.js";
import { hmacsign } from "./hmac.js";
import * as glog from "./log.js";
import { rayid } from "./req.js";
import * as dbx from "./sql/dbx.js";
import { crand, obfuscateHex } from "./webcrypto.js";

export const mincidlength = 32; // ideally 64 hex chars
export const mindidlength = 16; // ideally 32 hex chars

const kindplaystoreclient = 0;

const kindphone = 0;
// const kindbanned = -1;
const kindremoved = -2;
const log = new glog.Log("reg");

const clientmsg = str2byte("rethinkappclient");
const devicemsg = str2byte("rethinkappdevice");

export const didTokenHeader = "x-rethink-app-did-token";
// Adjustable validity period for the did token; default 3 days
const didTokenValiditySecs = 3 * 24 * 60 * 60;
const didTokenCtx = str2byte("rethinkappdidtoken");

/**
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request
 */
export async function registerClient(env, req) {
  if (req.method !== "POST") {
    return r405("method not allowed");
  }
  const ray = rayid(req);
  const url = new URL(req.url);
  const test = url.searchParams.has("test");
  const clientkind = url.searchParams.get("clientkind") || "0";
  const devicekind = url.searchParams.get("devicekind") || "0";
  const existingCid = url.searchParams.get("cid");
  const meta = await req.json();

  const clientkindint = parseInt(clientkind, 10) || kindplaystoreclient;
  const devicekindint = parseInt(devicekind, 10) || kindphone;

  // if a cid is provided, verify it was generated by us, then upsert client metadata only
  if (!emptyString(existingCid)) {
    if (
      existingCid.length < mincidlength ||
      !/^[a-fA-F0-9]+$/.test(existingCid)
    ) {
      return r400(`${ray} invalid cid`);
    }

    // re-derive the hmac key from the prefix half of the cid and verify the suffix
    const cidBytes = hex2buf(existingCid);
    const rand16 = cidBytes.slice(0, 16);
    const cidsig16claimed = cidBytes.slice(16, 32);

    try {
      const k = await hmacclientkey(env, rand16, test);
      if (!k) {
        return r500(`k unavailable: ${ray}`);
      }
      const cidmsg = cat(rand16, clientmsg);
      const cidsigbuf = await hmacsign(k, cidmsg);
      const cidsig16expected = new Uint8Array(cidsigbuf).slice(0, 16);

      if (!safeEq(cidsig16claimed, cidsig16expected)) {
        log.w(ray, "registerClient: cid invalid", existingCid);
        return r401(`cid verification failed: ${ray}`);
      } // else: ok
    } catch (e) {
      log.e(ray, "registerClient: cid verify error:", e);
      return r500(`${ray} error: ${e.message}`);
    }

    const clientmeta = meta?.client ?? null;
    try {
      const db = dbx.db2(env, test);
      const cout = await dbx.upsertClient(
        db,
        existingCid,
        clientmeta,
        clientkindint,
      );
      if (cout == null || !cout.success) {
        log.w(
          `${ray} registerClient upsert failed for ${existingCid}, test? ${test}`,
        );
        return r500(`${ray} could not re-register`);
      }
    } catch (e) {
      log.e(ray, "registerClient upsert error:", e);
      return r500(`${ray} db err: ${e.message}`);
    }

    log.d(ray, "registerClient updated cid:", existingCid, "test?", test);
    return r200j({ cid: existingCid });
  }

  try {
    const rand = crand(24);
    const rand16 = rand.slice(0, 16);
    const rand8 = rand.slice(16, 24);

    const k = await hmacclientkey(env, rand16, test);
    if (!k) {
      return r500(`k unavailable: ${ray}`);
    }

    const cidmsg = cat(rand16, clientmsg);
    const didmsg = cat(rand8, devicemsg);

    const allsigs = await Promise.all([
      hmacsign(k, cidmsg),
      hmacsign(k, didmsg),
    ]);

    const cidsig16 = new Uint8Array(allsigs[0]).slice(0, 16);
    const didsig8 = new Uint8Array(allsigs[1]).slice(0, 8);

    const cid = buf2hex(cat(rand16, cidsig16));
    const did = buf2hex(cat(rand8, didsig8));

    const clientmeta = meta?.client ?? null;
    const devicemeta = meta?.device ?? null;

    const db = dbx.db2(env, test);
    const cout = await dbx.insertClient(db, cid, clientmeta, clientkindint);
    if (cout == null || !cout.success) {
      return r500(`client insert failed: ${ray}`);
    }
    const dout = await dbx.upsertDevice(
      db,
      did,
      cid,
      devicemeta,
      devicekindint,
    );
    if (dout == null || !dout.success) {
      // TODO: delete cid from clients table since device insert failed,
      // to avoid orphaned client record
      return r500(`device insert failed: ${ray}`);
    }
    log.d(ray, "registerClient cid:", cid, "did:", did, "test?", test);
    return r200j({ cid: cid, did: did });
  } catch (e) {
    log.e(ray, "registerClient error:", e);
    return r500(`db error: ${ray}: ${e.message}`);
  }
}

/**
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request
 */
export async function registerDevice(env, req) {
  if (req.method !== "POST") {
    return r405("method not allowed");
  }
  if (!req.headers.get("Content-Type")?.includes("application/json")) {
    return r400("unsupported content type");
  }

  const ray = rayid(req);
  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400(`${ray} missing/invalid cid`);
  }

  // verify cid was generated by us
  const cidBytes = hex2buf(cid);
  const rand16 = cidBytes.slice(0, 16);
  const cidsig16claimed = cidBytes.slice(16, 32);

  // pre-parse did bytes (when provided) so cid+did sigs can run in parallel
  let rand8 = null;
  let didsig8claimed = null;
  if (!emptyString(did)) {
    if (did.length < mindidlength || !/^[a-fA-F0-9]+$/.test(did)) {
      return r400(`${ray} invalid did`);
    }
    const didBytes = hex2buf(did);
    rand8 = didBytes.slice(0, 8);
    didsig8claimed = didBytes.slice(8, 16);
  }

  let k;
  try {
    k = await hmacclientkey(env, rand16, test);
    if (!k) return r500(`k unavailable: ${ray}`);
  } catch (e) {
    log.e(ray, "registerDevice: key error:", e);
    return r500(`${ray} error: ${e.message}`);
  }

  // verify cid and did (when provided) sigs in parallel
  try {
    const cidmsg = cat(rand16, clientmsg);
    const sigs = await Promise.all([
      hmacsign(k, cidmsg),
      ...(rand8 != null ? [hmacsign(k, cat(rand8, devicemsg))] : []),
    ]);

    const cidsig16expected = new Uint8Array(sigs[0]).slice(0, 16);
    if (!safeEq(cidsig16claimed, cidsig16expected)) {
      log.w(ray, "registerDevice: cid invalid", cid);
      return r401(`cid verification failed: ${ray}`);
    }

    if (rand8 != null) {
      const didsig8expected = new Uint8Array(sigs[1]).slice(0, 8);
      if (!safeEq(didsig8claimed, didsig8expected)) {
        log.w(ray, "registerDevice: did invalid", did);
        return r401(`did verification failed: ${ray}`);
      }
    }
  } catch (e) {
    log.e(ray, "registerDevice: sig verify error:", e);
    return r500(`${ray} error: ${e.message}`);
  }

  let meta = null;
  try {
    meta = await req.json();
  } catch (_) {
    // body missing or not valid JSON; proceed with null meta
  }

  const clientmeta = meta?.client ?? null;
  const devicemeta = meta?.device ?? null;

  if (!emptyString(did)) {
    // both cid and did provided: upsert both tables (sigs already verified above)
    try {
      const db = dbx.db2(env, test);
      const cout = await dbx.upsertClient(
        db,
        cid,
        clientmeta,
        kindplaystoreclient,
      );
      if (cout == null || !cout.success) {
        return r500(`client upsert failed: ${ray}`);
      }
      const dout = await dbx.upsertDevice(db, did, cid, devicemeta, kindphone);
      if (dout == null || !dout.success) {
        return r500(`device upsert failed: ${ray}`);
      }
    } catch (e) {
      log.e(ray, "registerDevice upsert error:", e);
      return r500(`db error: ${ray}: ${e.message}`);
    }

    log.d(ray, "registerDevice updated cid:", cid, "did:", did, "test?", test);
    return retrieveDevices(env, cid, test, ray);
  }

  // only cid provided: generate a new did
  try {
    const rand8 = crand(8);
    const didmsg = cat(rand8, devicemsg);
    const didsigbuf = await hmacsign(k, didmsg);
    const didsig8 = new Uint8Array(didsigbuf).slice(0, 8);
    const newdid = buf2hex(cat(rand8, didsig8));

    const db = dbx.db2(env, test);
    const cout = await dbx.upsertClient(
      db,
      cid,
      clientmeta,
      kindplaystoreclient,
    );
    if (cout == null || !cout.success) {
      return r500(`client upsert failed: ${ray}`);
    }
    const dout = await dbx.upsertDevice(db, newdid, cid, devicemeta, kindphone);
    if (dout == null || !dout.success) {
      return r500(`device insert failed: ${ray}`);
    }

    log.d(ray, "registerDevice new did:", newdid, "for c:", cid, "test?", test);
    return r200j({ cid: cid, did: newdid });
  } catch (e) {
    // ex: Error: D1_ERROR: FOREIGN KEY constraint failed: SQLITE_CONSTRAINT
    log.e(ray, "registerDevice error:", e);
    return r500(`db error: ${ray}: ${e.message}`);
  }
}

/**
 * @param {any} env - Workers environment
 * @param {string} cid - Client identifier
 * @param {boolean} test - Test domain?
 */
export async function retrieveDevices(env, cid, test, ray = "") {
  if (
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400("invalid cid");
  }

  const db = dbx.db2(env, test);
  const out = await dbx.getDevices(db, cid);

  log.d(ray, "get dev for c:", cid, "test?", test, "found", out.success);

  if (out == null || !out.success) {
    return r500(`database error: ${ray}`);
  }
  if (out.results == null || out.results.length <= 0) {
    return r404(`no devices found: ${ray}`);
  }

  const json = [];
  for (const entry of out.results) {
    const did = entry.did || "";
    const obs = !emptyString(did) ? await obfuscateHex(did) : "";
    const meta = entry.meta != null ? JSON.parse(entry.meta) : null;
    const ctime =
      entry.ctime != null ? new Date(entry.ctime).toISOString() : null;
    const mtime =
      entry.mtime != null ? new Date(entry.mtime).toISOString() : null;
    // TODO: define json as class
    json.push({
      did: obs,
      meta: meta,
      created: ctime,
      updated: mtime,
    });
  }
  return r200j({ devices: json });
}

function r200j(j) {
  const h = { "content-type": "application/json" };
  return new Response(JSON.stringify(j), { status: 200, headers: h }); // ok
}

function r400(w) {
  return new Response(w, { status: 400 }); // bad request
}

function r404(w) {
  return new Response(w, { status: 404 }); // not found
}

function r405(w) {
  return new Response(w, { status: 405 }); // method not allowed
}

/**
 * Removes (soft-deletes) a device for the given client.
 * Sets kind = -2 on the device row so it is no longer active or enumerable.
 * @param {any} env - Workers environment
 * @param {Request} req - Incoming request with cid and did as query params
 * @returns {Promise<Response>}
 */
export async function removeDevice(env, req) {
  if (req.method !== "DELETE" && req.method !== "POST") {
    return r405("method not allowed");
  }

  const ray = rayid(req);
  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (
    emptyString(did) ||
    did.length < mindidlength ||
    !/^[a-fA-F0-9]+$/.test(did) ||
    emptyString(cid) ||
    cid.length < mincidlength ||
    !/^[a-fA-F0-9]+$/.test(cid)
  ) {
    return r400(`${ray} invalid identifiers`);
  }

  try {
    const db = dbx.db2(env, test);
    // kind = -2 marks device as removed (soft-delete)
    const out = await dbx.modifyDeviceKind(db, cid, did, kindremoved);
    if (out == null || !out.success || out.meta?.rowswritten === 0) {
      log.w(
        `${ray} removeDevice: no device found for c:${cid} d:${did} test?${test}; out: ${JSON.stringify(out)}`,
      );
      return r404(`device not found: ${ray}`);
    }
  } catch (e) {
    log.e(ray, "removeDevice error:", e);
    return r500(`db error: ${ray}: ${e.message}`);
  }

  log.d(ray, "remove", did, "for c:", cid, "test?", test);
  return r204(); // no content
}

function r204() {
  return new Response(null, { status: 204 }); // no content
}

function r401(w) {
  return new Response(w, { status: 401 }); // unauthorized
}

function r500(w) {
  return new Response(w, { status: 500 }); // internal server error
}

/**
 * Encodes an epoch (seconds) as a 4-byte big-endian Uint8Array.
 * @param {number} epochSecs
 * @returns {Uint8Array}
 */
function epoch2buf(epochSecs) {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, epochSecs >>> 0, false);
  return b;
}

/**
 * Generates a HMAC token binding cid and did with an expiry timestamp.
 * Token format: "<hmac_hex>:<expiry_epoch_secs>"
 * @param {CryptoKey} k - HMAC key (derived from cid's rand16 via hmacclientkey)
 * @param {string} cid - client id (hex)
 * @param {string} did - device id (hex)
 * @param {number} [validitySecs] - validity in seconds (default: didTokenValiditySecs)
 * @returns {Promise<string|null>} - token string or null on error
 */
async function generateDidToken(
  k,
  cid,
  did,
  validitySecs = didTokenValiditySecs,
) {
  try {
    const expiry = Math.floor(Date.now() / 1000) + validitySecs;
    const msg = lcat(
      didTokenCtx,
      hex2buf(cid),
      hex2buf(did),
      epoch2buf(expiry),
    );
    const sigbuf = await hmacsign(k, msg);
    const sig = buf2hex(new Uint8Array(sigbuf));
    return `${sig}:${expiry}`;
  } catch (e) {
    log.e("generateDidToken err:", e);
    return null;
  }
}

/**
 * Verifies a did token. Returns true only if the HMAC is valid and the token hasn't expired.
 * @param {CryptoKey} k - HMAC key (derived from cid's rand16 via hmacclientkey)
 * @param {string} cid - client id (hex)
 * @param {string} did - device id (hex)
 * @param {string} token - token string "<hmac_hex>:<expiry_epoch_secs>"
 * @returns {Promise<boolean>}
 */
async function verifyDidToken(k, cid, did, token) {
  try {
    const sep = token.lastIndexOf(":");
    if (sep < 0) return false;
    const claimedSigHex = token.slice(0, sep);
    const claimedExpiry = parseInt(token.slice(sep + 1), 10);
    if (
      isNaN(claimedExpiry) ||
      claimedExpiry <= Math.floor(Date.now() / 1000)
    ) {
      return false; // expired or unparseable
    }
    const msg = lcat(
      didTokenCtx,
      hex2buf(cid),
      hex2buf(did),
      epoch2buf(claimedExpiry),
    );
    const expectedSigBuf = await hmacsign(k, msg);
    const expectedSig = new Uint8Array(expectedSigBuf);
    const claimedSig = hex2buf(claimedSigHex);
    return safeEq(claimedSig, expectedSig);
  } catch (e) {
    log.e("verifyDidToken err:", e);
    return false;
  }
}

/**
 * 204 No Content response with the did token header set.
 * @param {string} token
 * @returns {Response}
 */
function r204token(token) {
  return new Response(null, {
    status: 204,
    headers: { [didTokenHeader]: token },
  });
}

/**
 * Verifies that the device (did) is registered for the client (cid) and isn't banned.
 * First verifies cid and did were generated by us (via the HMAC flow) before touching the DB.
 * If the request carries a valid "x-rethink-app-did-token" header the database check is
 * skipped entirely. On a successful database check a fresh token is minted and returned in
 * the "x-rethink-app-did-token" response header.
 * Callers should check resp.ok: false means the request is denied.
 * @param {any} env - Worker environment
 * @param {Request} req - The incoming request containing cid and did query parameters
 * @returns {Promise<Response>} 204 if authorized (token in header on new issue), error Response otherwise.
 */
export async function authorizeDevice(env, req) {
  const ray = rayid(req);
  const url = new URL(req.url);
  const cid = url.searchParams.get("cid");
  const did = url.searchParams.get("did");
  const test = url.searchParams.has("test");

  if (!cid || cid.length < mincidlength || !/^[a-fA-F0-9]+$/.test(cid)) {
    return r400("missing/invalid client id");
  }
  if (!did || did.length < mindidlength || !/^[a-fA-F0-9]+$/.test(did)) {
    return r400("missing/invalid device id");
  }

  // fast path: verify cid was generated by us before touching the database
  const cidBytes = hex2buf(cid);
  const rand16 = cidBytes.slice(0, 16);
  const cidsig16claimed = cidBytes.slice(16, 32);

  // pre-parse did bytes so both sigs can be computed in parallel
  const didBytes = hex2buf(did);
  const rand8 = didBytes.slice(0, 8);
  const didsig8claimed = didBytes.slice(8, 16);

  let k;
  try {
    k = await hmacclientkey(env, rand16, test);
    if (!k) return r500(`k unavailable: ${ray}`);
  } catch (e) {
    log.e(ray, "authorizeDevice: key error:", e);
    return r500(`${ray} err: ${e.message}`);
  }

  // verify cid and did sigs in parallel
  let cidsigbuf, didsigbuf;
  try {
    const cidmsg = cat(rand16, clientmsg);
    const didmsg = cat(rand8, devicemsg);
    [cidsigbuf, didsigbuf] = await Promise.all([
      hmacsign(k, cidmsg),
      hmacsign(k, didmsg),
    ]);
  } catch (e) {
    log.e(ray, "authorizeDevice: sig error:", e);
    return r500(`${ray} err: ${e.message}`);
  }

  const cidsig16expected = new Uint8Array(cidsigbuf).slice(0, 16);
  if (!safeEq(cidsig16claimed, cidsig16expected)) {
    log.w(ray, "authorizeDevice: cid invalid", cid);
    return r401("missing/invalid client id");
  }

  const didsig8expected = new Uint8Array(didsigbuf).slice(0, 8);
  if (!safeEq(didsig8claimed, didsig8expected)) {
    log.w(ray, "authorizeDevice: did invalid", did);
    return r401(`${ray} missing/invalid device id`);
  }

  // token fast path: skip the database if the client presents a valid did token
  const incomingToken = req.headers.get(didTokenHeader);
  if (!emptyString(incomingToken)) {
    const valid = await verifyDidToken(k, cid, did, incomingToken);
    if (valid) {
      log.d(ray, "authorizeDevice: token ok for", cid, ":", did);
      return r204(); // authorized; existing token still valid, no re-issue needed
    }
    log.d(ray, "authorizeDevice: token invalid/expired", cid, ":", did);
  }

  // fallback: verify via database
  let devres;
  try {
    devres = await dbx.getDevice(dbx.db2(env, test), cid, did);
  } catch (ex) {
    return r500(`db err: ${ex.message}`);
  }

  log.d(ray, "authorize:", cid, ":", did, "t?", test, "ok?", devres?.success);

  // getDevice excludes banned devices (kind != -1) and matches both cid+did;
  // no result means the device is unregistered or banned.
  if (
    devres == null ||
    !devres.success ||
    devres.results == null ||
    devres.results.length <= 0
  ) {
    return r401(`${ray} device not found`);
  }

  // device authorized via db: mint and return a fresh token
  const token = await generateDidToken(k, cid, did);
  if (emptyString(token)) {
    log.w(ray, "authorizeDevice: token gen err for", cid, ":", did);
    return r204(); // authorized but token issuance failed; proceed without it
  }
  return r204token(token);
}
